import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "ui-lab-components/styles.css"
import "./globals.css";

import ConvexClientProvider from "@/components/shared/convex-client-provider";
import { Sidebar } from "@/components/shared/sidebar";
import { TitleBar } from "@/components/shared/title-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/Logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-black" lang="en" suppressHydrationWarning>
      <body className={`bg-background-950/90 text-foreground-300 ${geistSans.variable} ${geistMono.variable}`}>
        <ConvexClientProvider>
          <div className="flex flex-col h-screen overflow-hidden">
            <TitleBar />
            <div className="flex flex-1 min-h-0">
              <Sidebar />
              <main className="flex-1 flex flex-col min-w-0 relative">
                {children}
              </main>
            </div>
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}

