import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "ui-lab-components/styles.css"
import "./globals.css";

import ConvexClientProvider from "../components/ConvexClientProvider";
import { Sidebar } from "../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-background-950 text-foreground-300 ${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex-1 overflow-y-auto">
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </div>
        </div>
      </body>
    </html>
  );
}

